M48
; DRILL file {KiCad 9.0.6} date 2026-01-14T23:26:52-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-01-14T23:26:52-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.048
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T3C3.988
%
G90
G05
T1
X233.11Y-15.1
X238.89Y-15.1
T2
X128.95Y-93.515
X167.05Y-93.515
T3
X128.95Y-108.725
X167.05Y-108.725
M30
